# Generated by Django 4.2.2 on 2023-07-01 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('trakt_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('tmdb_id', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('backdrop_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('trakt_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('season_number', models.PositiveIntegerField()),
                ('first_aired', models.DateField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytvtime.show')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('trakt_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('episode_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('first_aired', models.DateField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytvtime.season')),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytvtime.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'show')},
            },
        ),
        migrations.CreateModel(
            name='Watched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytvtime.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'episode')},
            },
        ),
    ]
