# Generated by Django 4.2.2 on 2023-07-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytvtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='tmdb_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
