# Generated by Django 4.2.3 on 2023-07-08 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mytvtime', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='users',
            field=models.ManyToManyField(related_name='shows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NextEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('season', models.IntegerField()),
                ('number', models.IntegerField()),
                ('air_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_episode', to='mytvtime.show')),
            ],
        ),
    ]
