# Generated by Django 4.2.3 on 2023-07-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytvtime', '0004_show_users_nextepisode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
